require("sanderson.plugins")
require("sanderson.remap")
require("sanderson.options")
require("sanderson.treesitter")
require("sanderson.rose-pine")
require("sanderson.lualine")
require("sanderson.telescope")
require("sanderson.lspconfig")
require("sanderson.nvim-tree")
require("sanderson.packer")
require("sanderson.beacon")
require("sanderson.toggleterm")
require("sanderson.tagbar")

